"""
Generated by CDK AWS Templates System
Project: ejemplo-basico
Description: Ejemplo básico de VPC con CDK Templates
Owner: equipo-infraestructura

DO NOT EDIT THIS FILE MANUALLY
This file is auto-generated from configuration files.
"""

#!/usr/bin/env python3

import aws_cdk as cdk
from stacks.ejemplo_basico_stack import Ejemplo_BasicoStack

app = cdk.App()

# Create stack for dev environment
Ejemplo_BasicoStack(
    app,
    "ejemplo-basico-dev",
    env=cdk.Environment(account="123456789012", region="us-east-1"),
    description="CDK stack for ejemplo-basico in dev",
)

app.synth()
