"""Property-based tests for Naming Convention Service."""

import re
import pytest
from hypothesis import given, settings, HealthCheck, assume
from hypothesis import strategies as st
from hypothesis.strategies import composite

from cdk_templates.naming_service import NamingConventionService


@composite
def naming_parameters_strategy(draw):
    """
    Generate random but valid naming parameters.
    
    Returns a dictionary with:
    - resource_type: AWS resource type
    - purpose: Purpose/role of the resource
    - environment: Environment name
    - region: AWS region
    - service: Service name (optional)
    - instance_number: Instance number (optional)
    """
    resource_type = draw(st.sampled_from([
        'vpc', 'ec2', 'rds', 's3', 'subnet', 'security_group',
        'iam_role', 'lambda', 'dynamodb', 'sns', 'sqs', 'cloudwatch_log_group'
    ]))
    
    # Generate valid component names (lowercase alphanumeric and hyphens)
    purpose = draw(st.text(
        min_size=3,
        max_size=20,
        alphabet='abcdefghijklmnopqrstuvwxyz0123456789-'
    ).filter(lambda x: x and not x.startswith('-') and not x.endswith('-') and '--' not in x))
    
    environment = draw(st.sampled_from(['dev', 'staging', 'prod', 'test', 'qa']))
    
    region = draw(st.sampled_from([
        'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2',
        'eu-west-1', 'eu-west-2', 'eu-central-1',
        'ap-southeast-1', 'ap-southeast-2', 'ap-northeast-1'
    ]))
    
    service = draw(st.one_of(
        st.none(),
        st.text(
            min_size=2,
            max_size=15,
            alphabet='abcdefghijklmnopqrstuvwxyz0123456789-'
        ).filter(lambda x: x and not x.startswith('-') and not x.endswith('-') and '--' not in x)
    ))
    
    instance_number = draw(st.one_of(
        st.none(),
        st.integers(min_value=1, max_value=99)
    ))
    
    return {
        'resource_type': resource_type,
        'purpose': purpose,
        'environment': environment,
        'region': region,
        'service': service,
        'instance_number': instance_number
    }


@composite
def multiple_naming_parameters_strategy(draw, resource_type=None):
    """
    Generate a list of naming parameters for the same resource type.
    Used to test uniqueness when multiple instances are created.
    """
    if resource_type is None:
        resource_type = draw(st.sampled_from(['vpc', 'ec2', 'rds', 's3']))
    
    count = draw(st.integers(min_value=2, max_value=10))
    
    # Use same environment, region, service for all instances
    environment = draw(st.sampled_from(['dev', 'staging', 'prod']))
    region = draw(st.sampled_from(['us-east-1', 'us-west-2', 'eu-west-1']))
    service = draw(st.text(
        min_size=2,
        max_size=10,
        alphabet='abcdefghijklmnopqrstuvwxyz0123456789-'
    ).filter(lambda x: x and not x.startswith('-') and not x.endswith('-') and '--' not in x))
    
    # Generate different purposes for each instance
    purposes = []
    for i in range(count):
        purpose = draw(st.text(
            min_size=3,
            max_size=15,
            alphabet='abcdefghijklmnopqrstuvwxyz0123456789-'
        ).filter(lambda x: x and not x.startswith('-') and not x.endswith('-') and '--' not in x))
        purposes.append(purpose)
    
    return [
        {
            'resource_type': resource_type,
            'purpose': purpose,
            'environment': environment,
            'region': region,
            'service': service,
            'instance_number': i + 1
        }
        for i, purpose in enumerate(purposes)
    ]


class TestNamingConventionProperties:
    """Property-based tests for Naming Convention Service."""

    @given(naming_parameters_strategy())
    @settings(
        max_examples=100,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
        deadline=5000
    )
    def test_property_1_naming_convention_application(self, params):
        """
        Feature: cdk-aws-templates-system
        Property 1: Naming Convention Application - For any resource configuration,
        when a name is generated by the Naming Convention Service, the generated
        name SHALL follow the pattern {environment}-{service}-{purpose}-{region}[-{instance}]
        and comply with AWS naming restrictions for that resource type.
        
        Validates: Requirements 1.2, 1.3
        """
        naming_service = NamingConventionService()
        
        # Generate name
        generated_name = naming_service.generate_name(
            resource_type=params['resource_type'],
            purpose=params['purpose'],
            environment=params['environment'],
            region=params['region'],
            service=params['service'],
            instance_number=params['instance_number']
        )
        
        # Verify name is not empty
        assert generated_name, "Generated name should not be empty"
        
        # Verify pattern structure
        # Expected pattern: {env}-{service}-{purpose}-{region}[-{instance}]
        # Note: service defaults to 'app' if not provided
        expected_service = params['service'] if params['service'] else 'app'
        
        # Build expected pattern components (normalized to lowercase)
        env_lower = params['environment'].lower()
        service_lower = expected_service.lower()
        purpose_lower = params['purpose'].lower()
        region_lower = params['region'].lower()
        
        # Check that the name contains the expected components
        # (after resource-specific transformations, exact matching may vary)
        name_lower = generated_name.lower()
        
        # For most resource types, the pattern should be preserved
        # S3 and RDS have special transformations, so we check more loosely
        if params['resource_type'] not in ['s3', 'rds']:
            # Verify the basic pattern is present
            assert env_lower in name_lower, \
                f"Environment '{env_lower}' not found in generated name '{generated_name}'"
            assert service_lower in name_lower, \
                f"Service '{service_lower}' not found in generated name '{generated_name}'"
            assert purpose_lower in name_lower, \
                f"Purpose '{purpose_lower}' not found in generated name '{generated_name}'"
            assert region_lower in name_lower, \
                f"Region '{region_lower}' not found in generated name '{generated_name}'"
        
        # If instance number provided, verify it's in the name
        if params['instance_number'] is not None:
            instance_str = f"{params['instance_number']:02d}"
            assert instance_str in generated_name, \
                f"Instance number '{instance_str}' not found in generated name '{generated_name}'"
        
        # Verify AWS resource-specific constraints
        validation_result = naming_service.validate_name(
            generated_name,
            params['resource_type']
        )
        
        assert validation_result.is_valid, \
            f"Generated name '{generated_name}' violates AWS constraints for {params['resource_type']}: " \
            f"{[e.message for e in validation_result.errors]}"
        
        # Verify no validation errors
        assert len(validation_result.errors) == 0, \
            f"Generated name has validation errors: {validation_result.errors}"
        
        # Verify resource-specific constraints
        max_length, pattern, _ = naming_service.RESOURCE_CONSTRAINTS.get(
            params['resource_type'],
            (255, r'^[a-zA-Z0-9\s._\-:/()#,@\[\]+=&;{}!$*]+$', 'Generic')
        )
        
        # Check length constraint
        assert len(generated_name) <= max_length, \
            f"Generated name length {len(generated_name)} exceeds maximum {max_length} for {params['resource_type']}"
        
        # Check character pattern
        assert re.match(pattern, generated_name), \
            f"Generated name '{generated_name}' does not match required pattern for {params['resource_type']}"
        
        # Resource-specific validations
        if params['resource_type'] == 's3':
            # S3 bucket names must be lowercase
            assert generated_name.islower(), \
                f"S3 bucket name '{generated_name}' must be lowercase"
            
            # Cannot start or end with hyphen
            assert not generated_name.startswith('-'), \
                f"S3 bucket name '{generated_name}' cannot start with hyphen"
            assert not generated_name.endswith('-'), \
                f"S3 bucket name '{generated_name}' cannot end with hyphen"
            
            # Cannot contain consecutive periods
            assert '..' not in generated_name, \
                f"S3 bucket name '{generated_name}' cannot contain consecutive periods"
            
            # Cannot be formatted as IP address
            assert not re.match(r'^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$', generated_name), \
                f"S3 bucket name '{generated_name}' cannot be formatted as IP address"
        
        elif params['resource_type'] == 'rds':
            # RDS identifiers must start with a letter
            assert generated_name[0].isalpha(), \
                f"RDS identifier '{generated_name}' must start with a letter"
            
            # Cannot end with hyphen
            assert not generated_name.endswith('-'), \
                f"RDS identifier '{generated_name}' cannot end with hyphen"
            
            # Cannot contain consecutive hyphens
            assert '--' not in generated_name, \
                f"RDS identifier '{generated_name}' cannot contain consecutive hyphens"
            
            # Must be lowercase
            assert generated_name.islower(), \
                f"RDS identifier '{generated_name}' must be lowercase"

    @given(multiple_naming_parameters_strategy())
    @settings(
        max_examples=50,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
        deadline=5000
    )
    def test_property_2_naming_uniqueness(self, params_list):
        """
        Feature: cdk-aws-templates-system
        Property 2: Naming Uniqueness - For any set of multiple resource
        configurations of the same type, the Naming Convention Service SHALL
        generate unique names for each instance.
        
        Validates: Requirements 1.4
        """
        naming_service = NamingConventionService()
        
        generated_names = []
        
        for params in params_list:
            name = naming_service.generate_name(
                resource_type=params['resource_type'],
                purpose=params['purpose'],
                environment=params['environment'],
                region=params['region'],
                service=params['service'],
                instance_number=params['instance_number']
            )
            generated_names.append(name)
        
        # Verify all names are unique
        unique_names = set(generated_names)
        assert len(generated_names) == len(unique_names), \
            f"Duplicate names generated: {[name for name in generated_names if generated_names.count(name) > 1]}"
        
        # Verify each name is valid
        for name in generated_names:
            validation_result = naming_service.validate_name(
                name,
                params_list[0]['resource_type']
            )
            assert validation_result.is_valid, \
                f"Generated name '{name}' is invalid: {[e.message for e in validation_result.errors]}"

    @given(
        st.sampled_from(['vpc', 'ec2', 'rds', 's3', 'lambda', 'iam_role', 'sqs', 'sns'])
    )
    @settings(
        max_examples=200,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
        deadline=5000
    )
    def test_property_3_invalid_name_rejection(self, resource_type):
        """
        Feature: cdk-aws-templates-system
        Property 3: Invalid Name Rejection - For any resource configuration with
        a name that violates the naming convention or AWS restrictions, the system
        SHALL reject the configuration with a descriptive error message.
        
        Validates: Requirements 1.5
        """
        naming_service = NamingConventionService()
        
        # Test multiple types of invalid names for each resource type
        invalid_names = []
        
        # Common invalid patterns
        invalid_names.extend([
            '',  # Empty name
            ' ',  # Whitespace only
            '\n\t',  # Control characters
            'a' * 500,  # Exceeds max length for all resource types
        ])
        
        # Resource-specific invalid patterns
        if resource_type == 's3':
            invalid_names.extend([
                'UPPERCASE-NAME',  # S3 must be lowercase
                'name-with-CAPS',  # Mixed case
                '-starts-with-hyphen',  # Cannot start with hyphen
                'ends-with-hyphen-',  # Cannot end with hyphen
                'has..consecutive.periods',  # Consecutive periods
                '192.168.1.1',  # IP address format
                'name_with_underscores',  # Underscores not allowed
                'name with spaces',  # Spaces not allowed
                'name!@#$%',  # Special characters
                'a' * 64,  # Exceeds 63 char limit
            ])
        elif resource_type == 'rds':
            invalid_names.extend([
                '123-starts-with-number',  # Must start with letter
                'name-ends-with-hyphen-',  # Cannot end with hyphen
                'has--consecutive-hyphens',  # Consecutive hyphens
                'NAME-WITH-CAPS',  # Must be lowercase
                'name_with_underscores',  # Underscores not allowed
                'name with spaces',  # Spaces not allowed
                'name!@#$',  # Special characters
                'a' * 64,  # Exceeds 63 char limit
            ])
        elif resource_type == 'lambda':
            invalid_names.extend([
                'name with spaces',  # Spaces not allowed
                'name!@#$%',  # Special characters
                'name/with/slashes',  # Slashes not allowed
                'name:with:colons',  # Colons not allowed
                'a' * 65,  # Exceeds 64 char limit
            ])
        elif resource_type == 'iam_role':
            invalid_names.extend([
                'name with spaces',  # Spaces not allowed
                'name!@#$%^&*()',  # Invalid special characters
                'name/with/slashes',  # Slashes not allowed
                'a' * 65,  # Exceeds 64 char limit
            ])
        elif resource_type in ['sqs', 'sns']:
            invalid_names.extend([
                'name with spaces',  # Spaces not allowed
                'name!@#$%',  # Special characters
                'name/with/slashes',  # Slashes not allowed
                'name:with:colons',  # Colons not allowed
                'a' * 300,  # Exceeds limit (80 for SQS, 256 for SNS)
            ])
        else:  # vpc, ec2, subnet, security_group
            invalid_names.extend([
                '\n\t\r',  # Control characters only
                'a' * 300,  # Exceeds 255 char limit
            ])
        
        # Test each invalid name
        for invalid_name in invalid_names:
            validation_result = naming_service.validate_name(invalid_name, resource_type)
            
            # Should be invalid
            assert not validation_result.is_valid, \
                f"Name '{invalid_name}' should be invalid for {resource_type} but was accepted"
            
            # Should have at least one error
            assert len(validation_result.errors) > 0, \
                f"Invalid name '{invalid_name}' should produce at least one error for {resource_type}"
            
            # Each error should have descriptive message
            for error in validation_result.errors:
                assert error.message, \
                    f"Error for '{invalid_name}' should have a message"
                assert len(error.message) > 10, \
                    f"Error message should be descriptive: '{error.message}'"
                assert error.error_code, \
                    f"Error for '{invalid_name}' should have an error code"
                assert error.field_path, \
                    f"Error for '{invalid_name}' should have a field path"
                assert error.severity in ['ERROR', 'WARNING'], \
                    f"Error severity should be ERROR or WARNING, got {error.severity}"
                
                # Verify error message mentions the resource type or constraint
                assert resource_type in error.message.lower() or \
                       any(keyword in error.message.lower() for keyword in 
                           ['length', 'character', 'empty', 'start', 'end', 'hyphen', 
                            'lowercase', 'letter', 'period', 'ip address']), \
                    f"Error message should mention resource type or specific constraint: '{error.message}'"

    @given(naming_parameters_strategy())
    @settings(
        max_examples=100,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
        deadline=5000
    )
    def test_property_1_naming_idempotency(self, params):
        """
        Feature: cdk-aws-templates-system
        Property 1 (Extended): Naming Idempotency - For any resource configuration,
        calling generate_name multiple times with the same parameters SHALL produce
        the same name.
        
        Validates: Requirements 1.2, 1.3
        """
        naming_service = NamingConventionService()
        
        # Generate name twice
        name1 = naming_service.generate_name(
            resource_type=params['resource_type'],
            purpose=params['purpose'],
            environment=params['environment'],
            region=params['region'],
            service=params['service'],
            instance_number=params['instance_number']
        )
        
        name2 = naming_service.generate_name(
            resource_type=params['resource_type'],
            purpose=params['purpose'],
            environment=params['environment'],
            region=params['region'],
            service=params['service'],
            instance_number=params['instance_number']
        )
        
        # Should be identical
        assert name1 == name2, \
            f"generate_name is not idempotent: '{name1}' != '{name2}'"

    @given(naming_parameters_strategy())
    @settings(
        max_examples=100,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
        deadline=5000
    )
    def test_property_1_naming_lowercase_normalization(self, params):
        """
        Feature: cdk-aws-templates-system
        Property 1 (Extended): Lowercase Normalization - For resource types that
        require lowercase names (S3, RDS), the naming service SHALL automatically
        normalize input to lowercase.
        
        Validates: Requirements 1.2, 1.3
        """
        naming_service = NamingConventionService()
        
        # Generate name
        generated_name = naming_service.generate_name(
            resource_type=params['resource_type'],
            purpose=params['purpose'],
            environment=params['environment'],
            region=params['region'],
            service=params['service'],
            instance_number=params['instance_number']
        )
        
        # For S3 and RDS, verify lowercase
        if params['resource_type'] in ['s3', 'rds']:
            assert generated_name.islower(), \
                f"{params['resource_type']} name '{generated_name}' should be lowercase"
