"""
Generated by CDK AWS Templates System
Project: ejemplo-basico
Description: Ejemplo básico de VPC con CDK Templates
Owner: equipo-infraestructura

DO NOT EDIT THIS FILE MANUALLY
This file is auto-generated from configuration files.
"""

import aws_cdk as cdk
from aws_cdk import (
    aws_ec2 as ec2,
    aws_logs as logs,
)
from constructs import Construct


class Ejemplo_BasicoStack(cdk.Stack):
    """CDK Stack generated by CDK AWS Templates System."""

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # VPC: dev-app-vpc-ejemplo-us-east-1
        # CIDR: 10.0.0.0/16, AZs: 2, NAT Gateways: 1

        vpc_ejemplo = ec2.Vpc(
            self,
            "vpc-ejemplo",
            vpc_name="dev-app-vpc-ejemplo-us-east-1",
            ip_addresses=ec2.IpAddresses.cidr("10.0.0.0/16"),
            max_azs=2,
            enable_dns_hostnames=True,
            enable_dns_support=True,
            nat_gateways=1,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="Public", subnet_type=ec2.SubnetType.PUBLIC, cidr_mask=24
                ),
                ec2.SubnetConfiguration(
                    name="Private",
                    subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS,
                    cidr_mask=24,
                ),
            ],
        )

        # Apply tags to VPC
        cdk.Tags.of(vpc_ejemplo).add("Environment", "dev")
        cdk.Tags.of(vpc_ejemplo).add("Project", "ejemplo-basico")
        cdk.Tags.of(vpc_ejemplo).add("Owner", "equipo-infraestructura")
        cdk.Tags.of(vpc_ejemplo).add("CostCenter", "ingenieria")
        cdk.Tags.of(vpc_ejemplo).add("ManagedBy", "cdk-template-system")
        cdk.Tags.of(vpc_ejemplo).add("Component", "networking")
        cdk.Tags.of(vpc_ejemplo).add("Purpose", "ejemplo")

        # VPC Flow Logs
        flow_log_group = logs.LogGroup(
            self,
            "vpc-ejemplo-flow-logs",
            log_group_name="/aws/vpc/dev-app-vpc-ejemplo-us-east-1-flow-logs",
            retention=logs.RetentionDays.ONE_MONTH,
            removal_policy=cdk.RemovalPolicy.DESTROY,
        )

        flow_log = ec2.FlowLog(
            self,
            "vpc-ejemplo-flow-log",
            resource_type=ec2.FlowLogResourceType.from_vpc(vpc_ejemplo),
            destination=ec2.FlowLogDestination.to_cloud_watch_logs(flow_log_group),
        )
